<?php 
/**
 * CoolMS2 Contact Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/contact for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsContact;

$type = $this->fieldset->get('type');
$this->fieldset->get('value')->setOption('twbs', [
    'icon' => function ($element) use ($type) {
        return $type->getValue() ? [
            'content'   => $type->getValue() === 'mobile' ? 'phone' : 'phone-alt',
            'placement' => 'prepend',
            'decorators' => [
                'inputGroupAddon',
            ],
        ] : null;
    },
    'type' => [
        'type' => 'element',
        'content' => 'type',
        'placement' => 'prepend',
        'class' => 'btn',
        'order' => 5950,
        'decorators' => [
            'inputGroupBtn',
        ],
    ],
]);
?>
<?= $this->formCollection($this->fieldset, true, false);
