<?php 
/**
 * CoolMS2 Contact Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/contact for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsContact;

$this->fieldset->get('value')->setOptions([
        'twbs' => [
            'decorators' => [
                'formControl',
                'type' => [
                    'type' => 'element',
                    'content' => 'type',
                    'placement' => 'prepend',
                    'class' => 'btn',
                    'decorators' => [
                        'inputGroupBtn',
                    ],
                ],
                'inputGroup',
                'controlLabel' => ['placement' => 'prepend', 'class' => 'sr-only'],
                'col',
                'formControlFeedback' => ['placement' => 'append'],
                'formGroup',
            ],
        ],
        'label_attributes' => ['twbs' => ['class' => 'control-label sr-only']]
    ]);
?>
<?= $this->formCollection($this->fieldset, true, false);
