<?php 
/**
 * CoolMS2 Contact Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/contact for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsContact;

$this->fieldset->get('value')->setOption('twbs', [
    'icon' => [
        'content' => 'link',
        'placement' => 'prepend',
    ],
    'removeButton' => function() use ($fieldset) {
        return $fieldset->getOption('allow_remove') ? [
            'type' => 'glyphicon',
            'content' => 'minus',
            'placement' => 'append',
            'order' => 5950,
            'decorators' => [
                'btn' => [
                    'class' => 'btn-danger',
                    'onclick' => <<<EOJ
return CmsCommon.Form.Collection.removeFieldset(this);
EOJ
                ],
                'inputGroupBtn',
            ],
        ] : [
            'placement' => false,
        ];
    },
    'feedback' => function() use ($fieldset) {
        return $fieldset->getOption('allow_remove') ? [
            'type' => 'FormControlFeedback',
            'style' => 'right:55px',
        ] : [
            'type' => 'FormControlFeedback',
        ];
    },
    'row' => [
        'data-counter' => $this->counter,
    ],
]);
?>
<?= $this->formCollection($this->fieldset, false, false);
